In [3]:
# import following library

import numpy as np

a= np.arange(6)
a2 = a[np.newaxis, :]
a2.shape


(1, 6)

# crating an array using numpy

In [5]:
food = np.array(["Pakora", "Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [6]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [7]:
type(price)

numpy.ndarray

In [8]:
type(food)

numpy.ndarray

In [9]:
len(price) #length

3

In [10]:
len(food)

3

In [12]:
price[0:] #indexing

array([5, 5, 5])

In [14]:
price.mean()

5.0

In [15]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [18]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# specify range
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
#specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
#line space
np.linspace(1 , 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [27]:
# specify ur data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [28]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# array functions



In [30]:
a= np.array([10, 12,2,5,6,7.0,3.4,2.6])
a

array([10. , 12. ,  2. ,  5. ,  6. ,  7. ,  3.4,  2.6])

In [32]:
a.sort()
a

array([ 2. ,  2.6,  3.4,  5. ,  6. ,  7. , 10. , 12. ])

In [33]:
b = np.array([32,6,5,4,82,100,54,6])
b

array([ 32,   6,   5,   4,  82, 100,  54,   6])

In [35]:
c= np.concatenate((a,b))
c

array([  2. ,   2.6,   3.4,   5. ,   6. ,   7. ,  10. ,  12. ,  32. ,
         6. ,   5. ,   4. ,  82. , 100. ,  54. ,   6. ])

In [36]:
c.sort()
c

array([  2. ,   2.6,   3.4,   4. ,   5. ,   5. ,   6. ,   6. ,   6. ,
         7. ,  10. ,  12. ,  32. ,  54. ,  82. , 100. ])

# 2 - D Arrays

In [39]:
a = np.array([[1,2],[6,7]])
a

array([[1, 2],
       [6, 7]])

In [40]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [42]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [6, 7],
       [6, 7],
       [8, 9]])

In [43]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 6, 7],
       [6, 7, 8, 9]])

In [45]:
d = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,4]]])
d

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 4]]])

In [47]:
# to find the number of dimensions
d.ndim

3

In [48]:
e = np.array([[5,6,7],[8,9,0],[10,11,12]])
e

array([[ 5,  6,  7],
       [ 8,  9,  0],
       [10, 11, 12]])

In [49]:
e.ndim

2

In [50]:
# number of elements
e.size

9

In [52]:
# shape
d.shape

(3, 2, 4)

In [57]:
f = np.arange(9)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
#reshape
f.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
#reshape
np.reshape(f, newshape=(1,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# conver 1-D array to 2-D array

In [61]:
g = np.array([1,2,3,4,5,6,7,8,9])
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
h = g[np.newaxis, :] # row wise
h

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [63]:
h.shape

(1, 9)

In [64]:
i = g[:,np.newaxis]  # column wise
i

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [65]:
g[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [66]:
g*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [67]:
g.sum()

45

In [68]:
g.mean()

5.0